name: ADHD
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - numpy
  - jax
  - jaxlib
  - pytorch
  - torchvision
  - opencv
  - pip
  - pip:
      - python-multipart  # in case you later add file uploads
