#! /bin/bash

docker buildx build -f "./Dockerfile" --tag "cuda_docker" --label "cuda_docker" . --build-arg NODE_VERSION="nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04"
# docker buildx build -f "./Dockerfile" --tag "cuda_docker" --label "cuda_docker" . --build-arg BUILD_JOBS=4 --build-arg SWAP_SIZE=8192 

# docker run -it cuda_docker:latest
docker run -it --rm --runtime=nvidia --gpus all cuda_docker:latest
