#! /bin/bash
compute_cap=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | tr -d '.')
echo $compute_cap

docker buildx build -f "./Dockerfile" --tag "cuda_docker" --label "cuda_docker" . --build-arg COMPUTE_CAP=$compute_cap
# docker buildx build -f "./Dockerfile" --tag "cuda_docker" --label "cuda_docker" . --build-arg BUILD_JOBS=4 --build-arg SWAP_SIZE=8192 

# docker run -it cuda_docker:latest
docker run -it --rm --runtime=nvidia --gpus all cuda_docker:latest
